### ISSUE TITLE
Making changes to kamailio.cfg?

### ISSUE THREAD

**Issue by pete1019** [evoseed/kamailio-tls-letsencrypt#2]
Hi,

thanks a lot for the project!

How would it be possible to edit the kamailio.cfg?
I see no volumes for that.

Thank you

**Comment by tommasinigiovanni** [comment]
Hi @pete1019 ,
thanks.

You are right, for kamailio's files there're no volume in docker-file; so you have 2 choices:
- modify the docker-compose adding this row in volume section `- ./module/kamailio/kamailio.cfg:/etc/kamailio/kamailio.cfg`
- modify `kamailio.cfg` and re-build the docker image

Being a development project by it seems a good idea to be able to change the `kamailio.cfg` on the go, so I added the volume in the `docker-file`: [1ff8c5a](https://github.com/evoseed/kamailio-tls-letsencrypt/commit/1ff8c5aafde085d72d3645be01939eb9958d3d34)
Now you just need to edit the `kamailio.cfg` and restart the container to running new `kamailio.cfg`

Cheers

**Comment by pete1019** [comment]
Hi @tommasinigiovanni 

thanks a lot for the fast reply.

Might there be other important config files in your opinion or are we set for now?

KR
